name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
            cpu: amd64
          - os: linux
            cpu: arm64
          - os: macos
            cpu: amd64
          - os: macos
            cpu: arm64
          - os: windows
            cpu: amd64
        include:
          - target:
              os: linux
              cpu: amd64
            builder: ubuntu-22.04
          - target:
              os: linux
              cpu: arm64
            builder: ubuntu-22.04-arm64
          - target:
              os: macos
              cpu: amd64
            builder: macos-13
          - target:
              os: macos
              cpu: arm64
            builder: macos-14
          - target:
              os: windows
              cpu: amd64
            builder: windows-2022
    
    runs-on: ${{ matrix.builder }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Restore Nim build cache
        uses: actions/cache@v4
        with:
          path: nim-build/cache
          key: nim-${{ matrix.target.os }}-${{ matrix.target.cpu }}-version-2-2
      
      - name: Setup Nim
        shell: bash
        run: |
          export NIM_COMMIT="version-2-2"
          mkdir -p nim-build
          bash scripts/ci/build_nim.sh nim-build/nim nim-build/csources nim-build/nimble nim-build/cache
          echo "$PWD/nim-build/nim/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        run: |
          nimble install -y --depsOnly
      
      - name: Build
        run: |
          nimble build -y
      
      - name: Run tests
        run: |
          nimble test -y